source("main.R")

parse_and_save_foia(yaml_file = "data/yaml/DHS.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/DOJ.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/DOL.yaml", method = "rds")
parse_and_save_foia(yaml_file = "yaml/DOS.yaml", method = "rds")
parse_and_save_foia(yaml_file = "yaml/EPA.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/HHS.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/DOI.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/GSA.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/SEC.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/VA.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/DOC.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/DOD.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/DOE.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/DOT.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/ED.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/HUD.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/SSA.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/Treasury.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/USAID.yaml", method = "rds")
parse_and_save_foia(yaml_file = "data/yaml/USDA.yaml", method = "rds")
